### ISSUE TITLE
Reference Error window is not defined 

### ISSUE THREAD

**Issue by Maccodonaldo** [ArturoRis/typescript-logger#4]
Using the typescript-logger in a node/express project the window. So it does not work in node

If the logger depends on the window object, the logger README.md file should not that it should not be used in a node-server environment

` ts-node-dev --respawn --transpileOnly ./src/server.ts`

`Using ts-node version 8.9.0, typescript version 3.8.3`
`ReferenceError: window is not defined`
    `at C:\...\node_modules\typescript-logger\build\loggerManager.js:102:9`
    `at C:\...\node_modules\typescript-logger\build\loggerManager.js:112:7`
   ` at Object.<anonymous> (C:\...\node_modules\typescript-logger\build\loggerManager.js:114:2)`

**Comment by silibdev** [comment]
Hi @Maccodonaldo,
I'm sorry for the very long wait but I published a new version fixing this bug 😉 

From now on the project will be more active 💪🏼
